# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window_low/UI_main_low.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_low(object):
    def setupUi(self, low):
        low.setObjectName("low")
        low.resize(646, 423)
        self.centralwidget = QtWidgets.QWidget(low)
        self.centralwidget.setObjectName("centralwidget")
        low.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(low)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 646, 26))
        self.menubar.setObjectName("menubar")
        low.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(low)
        self.statusbar.setObjectName("statusbar")
        low.setStatusBar(self.statusbar)

        self.retranslateUi(low)
        QtCore.QMetaObject.connectSlotsByName(low)

    def retranslateUi(self, low):
        _translate = QtCore.QCoreApplication.translate
        low.setWindowTitle(_translate("low", "MainWindow"))
